// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGXqpR5x4VD1NAmEMGd5BQKymNUB9kAL4',
    appId: '1:944935826804:web:5348fe9701bef78fae6821',
    messagingSenderId: '944935826804',
    projectId: 'moviebookingapp-49e70',
    authDomain: 'moviebookingapp-49e70.firebaseapp.com',
    storageBucket: 'moviebookingapp-49e70.firebasestorage.app',
    measurementId: 'G-98TSQ1JC77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfkj1NRmYXAiRvSv562bqRRLwvpCeIEnA',
    appId: '1:944935826804:android:84f49e9997651155ae6821',
    messagingSenderId: '944935826804',
    projectId: 'moviebookingapp-49e70',
    storageBucket: 'moviebookingapp-49e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqn-P60zGy4v-kQisawiciq3qY8e3Zbsw',
    appId: '1:944935826804:ios:e506b1e2fdde1ca2ae6821',
    messagingSenderId: '944935826804',
    projectId: 'moviebookingapp-49e70',
    storageBucket: 'moviebookingapp-49e70.firebasestorage.app',
    iosBundleId: 'com.example.cinecMoviebookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqn-P60zGy4v-kQisawiciq3qY8e3Zbsw',
    appId: '1:944935826804:ios:e506b1e2fdde1ca2ae6821',
    messagingSenderId: '944935826804',
    projectId: 'moviebookingapp-49e70',
    storageBucket: 'moviebookingapp-49e70.firebasestorage.app',
    iosBundleId: 'com.example.cinecMoviebookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGXqpR5x4VD1NAmEMGd5BQKymNUB9kAL4',
    appId: '1:944935826804:web:40f94a1822abb9e5ae6821',
    messagingSenderId: '944935826804',
    projectId: 'moviebookingapp-49e70',
    authDomain: 'moviebookingapp-49e70.firebaseapp.com',
    storageBucket: 'moviebookingapp-49e70.firebasestorage.app',
    measurementId: 'G-DSLMR147RW',
  );
}
